source ~/.dotfiles/config/global.sh
source ~/.dotfiles/config/local.zsh
source ~/.dotfiles/config/tab_title.zsh
source ~/.dotfiles/plugins/history-search-multi-word/history-search-multi-word.plugin.zsh

# Define the directories you store your projects in in
#   ~/.dotfiles/script/personal.zsh
#
# PROJECT_PARENT_DIRS+=("$HOME/Projects")

PROJECT_PARENT_DIRS=()
CD_ALIAS_GLOBS()

if [[ -f ~/.dotfiles/config/personal.zsh ]]; then
  source ~/.dotfiles/config/personal.zsh
fi

if [[ -f ~/.dotfiles/config/personal.sh ]]; then
  source ~/.dotfiles/config/personal.sh
fi

for CD_ALIAS_GLOB in ${CD_ALIAS_GLOBS[@]}; do
  for CD_ALIAS_DIR in ${~CD_ALIAS_GLOB}; do
    ALIAS=$(basename "${CD_ALIAS_DIR}")


    if $(echo $(which "${ALIAS}") | grep -q "not found"); then
      if [ -d "${CD_ALIAS_DIR}" ]; then
        alias "${ALIAS}"="cd \"${CD_ALIAS_DIR}\""
      fi
    fi
  done
done

for PARENT_DIR in ${PROJECT_PARENT_DIRS[@]} ; do
  if [ -d "$PARENT_DIR" ]; then
    for PROJECT_DIR in $(/bin/ls $PARENT_DIR); do
      if [[ ! -z `which $PROJECT_DIR 2> /dev/null` ]]; then
        if [ -d "$PARENT_DIR/$PROJECT_DIR" ]; then
          alias "$PROJECT_DIR"="cd $PARENT_DIR/$PROJECT_DIR"
        fi
      fi
    done
  fi
done

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
# stern completion
[[ -x /usr/local/bin/stern ]] && source <(stern --completion=zsh)
# helm completion
[[ -x /usr/local/bin/helm ]] && source <(helm completion zsh)
